### ISSUE TITLE
CfP menu item overlaps with logo

### ISSUE THREAD

**Issue by cgiovando** [openstreetmap/stateofthemap-2019#14]
On a standard 2560x1600 Mac display, tested in both Safari and Chrome, the first menu item (Call for Participation) overlaps with the main logo area and it's hard to read.

![Screen Shot 2019-04-24 at 13 57 57](https://user-images.githubusercontent.com/10201533/56657843-50044f80-6699-11e9-953c-66a32927cb02.jpg)

**Comment by Nakaner** [comment]
Is your browser window fullscreen/maximised? It looks to me that this is *not* an issue of width but of height. Taller windows (> 635 px) do not have this issue.

**Comment by tyrasd** [comment]
(oops, forgot to reply here yesterday) – I've added some margin to the logo section to always leave enough space for the navbar. This hopefully fixes the issue also on narrow browser windows.
