### ISSUE TITLE
Link to local chapters wrong?

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/stateofthemap-2019#27]
https://github.com/openstreetmap/stateofthemap-2019/blob/860066599a2c5df0dcdf9d666baef77b121062cf/sessions/8GY9WF.html#L17

Is this link intended to link to "Foundation" or "Foundation/Local Chapters"? Looks like it is supposed to link to the second option, but it actually links to "Foundation".

**Comment by tyrasd** [comment]
Thanks for the hint!
