### ISSUE TITLE
don't show "not-recorded" icon twice in program table

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/stateofthemap-2019#31]
One talk is currently both marked as non-recorded explicitly and is happening in a room that is not recorded anyway: [JJUFQT](https://2019.stateofthemap.org/sessions/JJUFQT/) – could the second non-recorded icon be dropped for such talks?

**Comment by Nakaner** [comment]
It could be dropped in the table. Its presence has no special/secret meaning in the table.

The details page contains the icon if either the speaker objected or the room is not recorded at all.
