### ISSUE TITLE
Remove Message of Greeting?

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/stateofthemap-2019#44]
The conference is over now. Can the message of greeting be removed?

I ask because it is hosted at www.openstreetmap.de as a temporary solution. Last week, I decided to host it there because FOSSGIS e.V. is already mentioned in the OSMF Privacy Policy and Youtube is not.

If we should keep it, I would deep-link to `https://media.ccc.de/v/sotm2019-2628-keynote-open-up-why-digital-mobility-needs-participation/oembed#t=1195` and ask the LWG to add media.ccc.de to the Privacy Policy.

**Comment by ChristineKarch** [comment]
I would like to keep it, but at media.ccc.de

**Comment by tyrasd** [comment]
or just use the platform the ministry used to publish the video? https://twitter.com/digitalmobilBW/status/1174222885969387520
